# -*- coding: utf-8 -*-
"""categorical-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iC9tjlfrSH-Q2i3qlsWhWKQsH58VYm0I
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {'Approximate Plant Age (weeks)': [1, 5, 10, 15, 20],
        'Indoor Or Outdoor?': ['Indoor', 'Outdoor', 'Indoor', 'Outdoor', 'Indoor'],
        'How Often Do You Water?': ['Daily', 'Weekly', 'Monthly', 'Never', 'Daily'],
        }
df = pd.DataFrame(data)
print(f"Plant data : \n{df}")

# Normalize numeric values
df['Approximate Plant Age (weeks)'] = (df['Approximate Plant Age (weeks)'] - df['Approximate Plant Age (weeks)'].min()) / (df['Approximate Plant Age (weeks)'].max() - df['Approximate Plant Age (weeks)'].min())
# print(f"\n Normalized Plant numeric data : \n{df}")

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
# Check categorical columns
# print(f"\n Categorical columns: {categorical_columns}")
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))
# Encoded categorical data
# print(f"\n Encoded Plant categorical data : \n{one_hot_df}")
df_encoded = pd.concat([df, one_hot_df], axis=1)

df_encoded = df_encoded.drop(categorical_columns, axis=1)
print(f"Encoded Plant data : \n{df_encoded}")

import numpy as np

feature_vector = df_encoded.values
print(f"Feature vector shape: {feature_vector.shape}")
print(f"Feature vector: \n {feature_vector}")

import torch
metadata_tensor = torch.tensor(feature_vector, dtype=torch.float32)
print(f"Metadata tensor shape: {metadata_tensor.shape}")
print(f"Metadata tensor: \n {metadata_tensor}")