# -*- coding: utf-8 -*-
"""Disease-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bjefIT-XhERXtJRUZ7ZOxWI9P-VNWro
"""

from torchvision import models
import torch

trained_model = torch.load("/home/abcrubaugh/mobilenet_v3_large_plants.pth")

model = models.mobilenet_v3_large(weights=None)

model.load_state_dict(trained_model)

disease_model = model

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device);
disease_model.to(device)

import kagglehub

# Download latest version
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print("Path to dataset files:", path)

import pandas as pd
import os
dataset_files = "/kaggle/input/new-plant-diseases-dataset"
os.listdir(dataset_files)